# ./dbt/profiles/profiles.yml

my_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: admin
      password: password
      port: 5432
      dbname: admin
      schema: public
      threads: 4

